# Generated by Django 2.2.5 on 2020-04-04 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_acitvityperiod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acitvityperiod',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='acitvityperiod',
            name='stop_date',
        ),
        migrations.AddField(
            model_name='acitvityperiod',
            name='data',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='acitvityperiod',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Name'),
        ),
        migrations.AlterField(
            model_name='name',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
