# Generated by Django 2.2.5 on 2020-04-04 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20200404_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acitvityperiod',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Name'),
        ),
        migrations.AlterField(
            model_name='name',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='name',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
