# Generated by Django 2.2.5 on 2020-04-04 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20200404_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acitvityperiod',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Name'),
        ),
        migrations.AlterField(
            model_name='name',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
